### ISSUE TITLE
New Bug: Pitch Tuning

### ISSUE THREAD

**Issue by Bumblebee001** [GrandOrgue/GoOdf#101]
This is called: _**Manual tuning**_ on GrandOrgue apparently.

Hence, changes in the GOodf do not appear on GrandOrgue so unlikely to have been applied.

I also noticed that changes I made on GO are not showing up on the reloaded odf in GOodf (unlike the changes in gain I made on the odf which showed up on GO [save the above issue]).

Regards
Mark

**Comment by larspalo** [comment]
> Hence, changes in the GOodf do not appear on GrandOrgue so unlikely to have been applied.

Wrong, just test with some more extreme values. The tones of many stops in for instance the BureaChoir sample set are interpolated from the just 4 pipe samples per octave (-D, -D#, -G# and -A) but the many -200 and +200 PitchTuning values that are present in the odf is not at all visible in GO - the pipes just sound approximately in tune...

Anyway, here's how that works:

The PitchTuning (and PitchCorrection) values that a sample set creator writes in the odf are not visible inside of GO for an user since quite a long time when we reworked the tunings to work in every possible scenario (whether in Original temperament or in any other selected temperament).

The values of Manual Tuning (and Auto Correction Tuning) that (only) the user can set from within GO are further adjustments, on top of any values from odf, that in turn are only saved into the settings .cmb file(s) and such values can be reverted back to the default values provided by the odf. Those values naturally are not available in the .organ file as they are called PitchTuning and PitchCorrection there!

AmplitudeLevel and Gain values from the odf on the other hand will be visible in GO as they are not affected by changing temperaments.

However, if one is very careful, it's still possible to import, with the GoOdf Tools->Import .cmb, the voicing settings for the tunings (and also amplitude/gain) that an user has set in a .cmb file to what is the corresponding values in the .organ file... There is no closer connection than that between what a user does from within GO and what a sample set producer can do in GoOdf so I'm a bit uncertain what you meant by:

> I also noticed that changes I made on GO are not showing up on the reloaded odf in GOodf

What exactly were you expecting?
