### ISSUE TITLE
How do I run this on a mac?

### ISSUE THREAD

**Issue by CoderOfPythonCode** [GrandOrgue/GoOdf#77]
I don't know how to run this on mac and I would love some advice, nvm I figured it out

**Comment by larspalo** [comment]
Either it must be compiled for mac, or you could try using the windows binary "crossover" style.

Personally I don't have access to any kind of mac OS X type of machine, which is also why I've not provided a build target for that when I do releases. If someone can come up with what changes are needed in the .github/workflow file (and very likely in the cmake files/other sources too) I could gladly add that, but I don't have any means to test it - which is why I cannot reliably support it either.

**Comment by CoderOfPythonCode** [comment]
Oh I take it back, i got a new pc with ubuntu and windows, all good

**Comment by MStraeten** [comment]
you might use macports to install the prerequisites
After installing macports: 
`sudo port -N install cmake wxWidgets-3.2 imagemagick
sudo port select --set wxWidgets wxWidgets-3.2 `
maybe also possible via homebrew …
then build as described here: https://github.com/GrandOrgue/GoOdf#building-from-sources

**Comment by CoderOfPythonCode** [comment]
Oh I figured it out, it's more simple than that it's more like 
`brew install wxwidgets`, and instead of using the latest release which has a bunch of errors use v8

**Comment by larspalo** [comment]
If someone figures out what changes are needed (in workflow file, cmake file and/or other source files) to publish releases of GoOdf ported to Mac here on GitHub (and also has the means to actually test them), I'll be happy to add it as long as it doesn't causes issues for the other platforms. But as I said earlier, I have no possibility to test/verify any ports to Mac myself.

**Comment by MStraeten** [comment]
you might try this build: [GOODF.zip](https://mega.nz/file/GWBTGAKa#pzWTcPOhSeJVU23PMWkPCQm5BL4oFbrDLgM3T4GfPbQ)
built with deployment target 11.3 for arm64
since all dependencies are present on my mac i can't check if all were properly integrated into the package - so please give feedback if it properly works.
then i can compile the steps into a macports based build & packaging script that can be provided here ...

**Comment by larspalo** [comment]
Please, focus the efforts into what changes are needed in the cmake file (CMakeLists.txt) in the root to be able to create a macOS build with the .github/workflows/release.yml file like GrandOrgue does to create the osx.x86_64.dmg release file (or whatever works to use on macOS).

**Comment by larspalo** [comment]
Since version 0.13.0 there are now builds released for MacOS with both Intel and arm64 architectures.
