### ISSUE TITLE
Comment lines removed

### ISSUE THREAD

**Issue by 1secureweb** [GrandOrgue/GoOdf#93]
I am new to GOODF. First thing I noted was the improved cleanness in my updated orgue file and a great way to update to latest version. However I also saw that my comment lines are removed.

As a programmer, I am used to inserting comments both for myself and for others to follow. My comments are usually one line at the object level, rather than additional comment tacked on to the end of a line. Often the comments are about sources of samples, or explicit reference to source of borrowing.
Not a major issue as, knowing in advance, I can document elsewhere but thought I'd mention it.

**Comment by larspalo** [comment]
Yes, that's highly intentional, not to mention functional (when the comment is on the same line as key=value). The very essence and goal of this tool however is to completely eliminate any interest in manual text interaction with the .organ file. Some might disagree with that, but that's my approach and firm belief in order to raise the quality of the odf.
