### ISSUE TITLE
Text runs out of page when window not optimized

### ISSUE THREAD

**Issue by Bumblebee001** [GrandOrgue/GoOdf#99]
Hi,

I noticed that the default window that opens up is not optimised such that text/ features run off the screen and are invisible.

For text to appear correctly, one has to widen the window.

I am using Windows 11 with default screen resolution 2880x1620  (as well as an extended screen with resolution 1920x1080).

![Screenshot 2024-05-16 065504](https://github.com/GrandOrgue/GoOdf/assets/6999990/9495e6f3-8210-4b31-a08e-192e5c962296)

**Comment by Bumblebee001** [comment]
The answer to your two questions: Yes and yes.

**Comment by larspalo** [comment]
Ok, interesting. I see that on the [Organ] panel things seem to work as I intended, so that the size of the right side panel cannot be made smaller than the contained elements allow. The Rank or Stop/Internal Rank panel on the other hand can be made too small, which results in some of the gui objects being pushed out of the screen. I'll investigate that and see if I can find a fix for it.
